# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turnikee.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TurnikeDurum(object):
    def setupUi(self, TurnikeDurum):
        TurnikeDurum.setObjectName("TurnikeDurum")
        TurnikeDurum.resize(220, 293)
        self.centralwidget = QtWidgets.QWidget(TurnikeDurum)
        self.centralwidget.setObjectName("centralwidget")
        self.lne_last_turnike = QtWidgets.QLineEdit(self.centralwidget)
        self.lne_last_turnike.setEnabled(False)
        self.lne_last_turnike.setGeometry(QtCore.QRect(10, 80, 191, 20))
        self.lne_last_turnike.setObjectName("lne_last_turnike")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.lne_cardid_turnike = QtWidgets.QLineEdit(self.centralwidget)
        self.lne_cardid_turnike.setEnabled(False)
        self.lne_cardid_turnike.setGeometry(QtCore.QRect(10, 130, 191, 20))
        self.lne_cardid_turnike.setObjectName("lne_cardid_turnike")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lne_first_turnike = QtWidgets.QLineEdit(self.centralwidget)
        self.lne_first_turnike.setEnabled(False)
        self.lne_first_turnike.setGeometry(QtCore.QRect(10, 30, 191, 20))
        self.lne_first_turnike.setObjectName("lne_first_turnike")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 61, 16))
        self.label_3.setObjectName("label_3")
        self.lne_cusType_turnike = QtWidgets.QLineEdit(self.centralwidget)
        self.lne_cusType_turnike.setEnabled(False)
        self.lne_cusType_turnike.setGeometry(QtCore.QRect(10, 180, 191, 20))
        self.lne_cusType_turnike.setObjectName("lne_cusType_turnike")
        self.lbl_status_turnike = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status_turnike.setGeometry(QtCore.QRect(10, 210, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_status_turnike.setFont(font)
        self.lbl_status_turnike.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_status_turnike.setObjectName("lbl_status_turnike")
        TurnikeDurum.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TurnikeDurum)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 220, 21))
        self.menubar.setObjectName("menubar")
        TurnikeDurum.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TurnikeDurum)
        self.statusbar.setObjectName("statusbar")
        TurnikeDurum.setStatusBar(self.statusbar)

        self.retranslateUi(TurnikeDurum)
        QtCore.QMetaObject.connectSlotsByName(TurnikeDurum)

    def retranslateUi(self, TurnikeDurum):
        _translate = QtCore.QCoreApplication.translate
        TurnikeDurum.setWindowTitle(_translate("TurnikeDurum", "Turnike Durum"))
        self.label.setText(_translate("TurnikeDurum", "Ad"))
        self.label_4.setText(_translate("TurnikeDurum", "CardID"))
        self.label_2.setText(_translate("TurnikeDurum", "Soyad"))
        self.label_3.setText(_translate("TurnikeDurum", "Müşteri Türü"))
        self.lbl_status_turnike.setText(_translate("TurnikeDurum", "X"))
