# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tireaso_qt_com_ports.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComPortWindow(object):
    def setupUi(self, ComPortWindow):
        ComPortWindow.setObjectName("ComPortWindow")
        ComPortWindow.resize(282, 285)
        self.centralwidget = QtWidgets.QWidget(ComPortWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_choose = QtWidgets.QPushButton(self.centralwidget)
        self.btn_choose.setGeometry(QtCore.QRect(10, 210, 161, 31))
        self.btn_choose.setObjectName("btn_choose")
        self.comList = QtWidgets.QListWidget(self.centralwidget)
        self.comList.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.comList.setObjectName("comList")
        self.btn_reflesh = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reflesh.setGeometry(QtCore.QRect(190, 210, 81, 31))
        self.btn_reflesh.setObjectName("btn_reflesh")
        ComPortWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ComPortWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 21))
        self.menubar.setObjectName("menubar")
        ComPortWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ComPortWindow)
        self.statusbar.setObjectName("statusbar")
        ComPortWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ComPortWindow)
        QtCore.QMetaObject.connectSlotsByName(ComPortWindow)

    def retranslateUi(self, ComPortWindow):
        _translate = QtCore.QCoreApplication.translate
        ComPortWindow.setWindowTitle(_translate("ComPortWindow", "Com Ports"))
        self.btn_choose.setText(_translate("ComPortWindow", "Seç"))
        self.btn_reflesh.setText(_translate("ComPortWindow", "Yenile"))
