# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turnike.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TurnikePort(object):
    def setupUi(self, TurnikePort):
        TurnikePort.setObjectName("TurnikePort")
        TurnikePort.resize(283, 283)
        self.centralwidget = QtWidgets.QWidget(TurnikePort)
        self.centralwidget.setObjectName("centralwidget")
        self.comList_Turnike = QtWidgets.QListWidget(self.centralwidget)
        self.comList_Turnike.setGeometry(QtCore.QRect(10, 10, 261, 192))
        self.comList_Turnike.setObjectName("comList_Turnike")
        self.btn_reflesh_turnike = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reflesh_turnike.setGeometry(QtCore.QRect(190, 210, 81, 31))
        self.btn_reflesh_turnike.setObjectName("btn_reflesh_turnike")
        self.btn_choose_turnike = QtWidgets.QPushButton(self.centralwidget)
        self.btn_choose_turnike.setGeometry(QtCore.QRect(10, 210, 161, 31))
        self.btn_choose_turnike.setObjectName("btn_choose_turnike")
        TurnikePort.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TurnikePort)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 283, 21))
        self.menubar.setObjectName("menubar")
        TurnikePort.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TurnikePort)
        self.statusbar.setObjectName("statusbar")
        TurnikePort.setStatusBar(self.statusbar)

        self.retranslateUi(TurnikePort)
        QtCore.QMetaObject.connectSlotsByName(TurnikePort)

    def retranslateUi(self, TurnikePort):
        _translate = QtCore.QCoreApplication.translate
        TurnikePort.setWindowTitle(_translate("TurnikePort", "MainWindow"))
        self.btn_reflesh_turnike.setText(_translate("TurnikePort", "Yenile"))
        self.btn_choose_turnike.setText(_translate("TurnikePort", "Seç"))
